# Generated by Django 3.1.2 on 2020-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_article_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvmsg',
            name='content',
            field=models.CharField(default='', max_length=200),
        ),
    ]
